/**
 * @file bondFunctions.h
 * @brief Provides host/device bond response and mixed-mode fracture formulas.
 */
#pragma once

#include "math/Vector3.h"

namespace fundem::execution
{

using math::Real;
using math::Vec3;

/**
 * Calculates the force, endpoint couples and elastic energies of one virtual bond.
 * The returned force acts on the master endpoint; the slave receives its opposite.
 * Endpoint torques exclude the moment generated by the force lever arm.
 * @p axialDisplacement is positive in axial opening and negative in compression.
 */
FUNDEM_MATH_HD inline void calculateBondForceAndTorque(Vec3& force,
                                                       Vec3& masterTorque,
                                                       Vec3& slaveTorque,
                                                       Vec3& normal,
                                                       Real& axialDisplacement,
                                                       Real& normalElasticEnergy,
                                                       Real& shearElasticEnergy,
                                                       Real& bendingElasticEnergy,
                                                       Real& torsionalElasticEnergy,
                                                       const Vec3& masterEndpointPosition,
                                                       const Vec3& slaveEndpointPosition,
                                                       const Vec3& masterEndpointNormal,
                                                       const Vec3& masterEndpointTangent1,
                                                       const Vec3& masterEndpointTangent2,
                                                       const Vec3& slaveEndpointNormal,
                                                       const Vec3& slaveEndpointTangent1,
                                                       const Vec3& slaveEndpointTangent2,
                                                       Real coefficientB1,
                                                       Real coefficientB2,
                                                       Real coefficientB3,
                                                       Real coefficientB4,
                                                       Real equivalentLength) noexcept
{
    const Vec3 endpointSeparation = masterEndpointPosition - slaveEndpointPosition;
    const Real currentLength = math::norm(endpointSeparation);
    Real inverseLength = 0.0;
    if (currentLength > 0.0)
    {
        inverseLength = 1.0 / currentLength;
    }
    normal = currentLength > 0.0 ? endpointSeparation / currentLength : -masterEndpointNormal;
    const Vec3 masterToSlaveDirection = -normal;
    axialDisplacement = currentLength - equivalentLength;
    normalElasticEnergy = 0.5 * coefficientB1 * axialDisplacement * axialDisplacement;
    shearElasticEnergy = coefficientB2 * (0.5 * math::dot(slaveEndpointNormal - masterEndpointNormal, masterToSlaveDirection) - 0.25 * math::dot(masterEndpointNormal, slaveEndpointNormal) + 0.75);
    bendingElasticEnergy = (0.25 * coefficientB2 + coefficientB3 + 0.5 * coefficientB4) * (math::dot(masterEndpointNormal, slaveEndpointNormal) + 1.0);
    torsionalElasticEnergy =
        -0.5 * coefficientB4 *
        (math::dot(masterEndpointNormal, slaveEndpointNormal) + math::dot(masterEndpointTangent1, slaveEndpointTangent1) + math::dot(masterEndpointTangent2, slaveEndpointTangent2) - 1.0);

    force =
        coefficientB1 * axialDisplacement * masterToSlaveDirection +
        0.5 * inverseLength * coefficientB2 * ((slaveEndpointNormal - masterEndpointNormal) - math::dot(slaveEndpointNormal - masterEndpointNormal, masterToSlaveDirection) * masterToSlaveDirection);
    const Vec3 torsionBendingTorque = coefficientB3 * math::cross(slaveEndpointNormal, masterEndpointNormal) -
                                      0.5 * coefficientB4 * (math::cross(slaveEndpointTangent1, masterEndpointTangent1) + math::cross(slaveEndpointTangent2, masterEndpointTangent2));
    masterTorque = -0.5 * coefficientB2 * math::cross(masterToSlaveDirection, masterEndpointNormal) + torsionBendingTorque;
    slaveTorque = 0.5 * coefficientB2 * math::cross(masterToSlaveDirection, slaveEndpointNormal) - torsionBendingTorque;
}

/** Returns the Benzeggagh-Kenane mixed-mode critical energy release rate. */
FUNDEM_MATH_HD inline Real calculateBKCriticalEnergy(Real modeIEnergyReleaseRate, Real modeIIEnergyReleaseRate, Real modeICriticalEnergy, Real modeIICriticalEnergy, Real modeMixityExponent) noexcept
{
    const Real positiveModeI = modeIEnergyReleaseRate > 0.0 ? modeIEnergyReleaseRate : 0.0;
    const Real positiveModeII = modeIIEnergyReleaseRate > 0.0 ? modeIIEnergyReleaseRate : 0.0;
    const Real totalEnergyReleaseRate = positiveModeI + positiveModeII;
    if (totalEnergyReleaseRate <= math::defaultTolerance)
    {
        return 0.0;
    }

    const Real modeIIFraction = positiveModeII / totalEnergyReleaseRate;
    return modeICriticalEnergy + (modeIICriticalEnergy - modeICriticalEnergy) * math::detail::pow(modeIIFraction, modeMixityExponent);
}

/**
 * Updates irreversible BK damage and returns true once the bond has completely failed.
 * Normal elastic energy contributes to mode I only during axial opening.
 * A zero cross-sectional area disables further damage evolution.
 */
FUNDEM_MATH_HD inline bool updateBKDamage(Real& damageFactor,
                                          Real& maximumEnergyReleaseRatio,
                                          Real axialDisplacement,
                                          Real normalElasticEnergy,
                                          Real shearElasticEnergy,
                                          Real bendingElasticEnergy,
                                          Real torsionalElasticEnergy,
                                          Real crossSectionArea,
                                          Real modeICriticalEnergy,
                                          Real modeIICriticalEnergy,
                                          Real modeMixityExponent,
                                          Real damageInitiationRatio) noexcept
{
    if (damageFactor >= 1.0)
    {
        damageFactor = 1.0;
        return true;
    }
    if (crossSectionArea <= 0.0)
    {
        return false;
    }

    const Real openingNormalElasticEnergy = axialDisplacement > 0.0 ? normalElasticEnergy : 0.0;
    const Real modeIElasticEnergy = openingNormalElasticEnergy + bendingElasticEnergy;
    const Real modeIIElasticEnergy = shearElasticEnergy + torsionalElasticEnergy;
    const Real modeIEnergyReleaseRate = (modeIElasticEnergy > 0.0 ? modeIElasticEnergy : 0.0) / crossSectionArea;
    const Real modeIIEnergyReleaseRate = (modeIIElasticEnergy > 0.0 ? modeIIElasticEnergy : 0.0) / crossSectionArea;
    const Real totalEnergyReleaseRate = modeIEnergyReleaseRate + modeIIEnergyReleaseRate;
    if (totalEnergyReleaseRate <= math::defaultTolerance)
    {
        return false;
    }

    const Real criticalEnergy = calculateBKCriticalEnergy(modeIEnergyReleaseRate, modeIIEnergyReleaseRate, modeICriticalEnergy, modeIICriticalEnergy, modeMixityExponent);
    if (criticalEnergy <= math::defaultTolerance)
    {
        return false;
    }

    if (damageInitiationRatio >= 1.0)
    {
        if (totalEnergyReleaseRate >= criticalEnergy)
        {
            damageFactor = 1.0;
            const Real energyReleaseRatio = totalEnergyReleaseRate / criticalEnergy;
            maximumEnergyReleaseRatio = maximumEnergyReleaseRatio > energyReleaseRatio ? maximumEnergyReleaseRatio : energyReleaseRatio;
            return true;
        }
        return false;
    }
    if (damageInitiationRatio <= 0.0)
    {
        return false;
    }

    const Real initiationEnergy = damageInitiationRatio * criticalEnergy;
    const Real energyReleaseRatio = totalEnergyReleaseRate / initiationEnergy;
    maximumEnergyReleaseRatio = maximumEnergyReleaseRatio > energyReleaseRatio ? maximumEnergyReleaseRatio : energyReleaseRatio;
    if (maximumEnergyReleaseRatio > 1.0)
    {
        Real updatedDamage = (maximumEnergyReleaseRatio - 1.0) / (1.0 / damageInitiationRatio - 1.0);
        if (updatedDamage < 0.0)
        {
            updatedDamage = 0.0;
        }
        else if (updatedDamage > 1.0)
        {
            updatedDamage = 1.0;
        }
        damageFactor = damageFactor > updatedDamage ? damageFactor : updatedDamage;
    }
    return damageFactor >= 1.0;
}

} // namespace fundem::execution
